# Generated by Django 3.0.1 on 2020-08-19 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='choices',
            field=models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')], default=True),
        ),
        migrations.AddField(
            model_name='boastroast',
            name='ghost_posts',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='boastroast',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
