# Generated by Django 3.0.1 on 2020-08-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200819_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastroast',
            old_name='ghost_posts',
            new_name='user_input',
        ),
    ]
