# Generated by Django 3.0.1 on 2020-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200819_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
